### ISSUE TITLE
ImportError: No module named fabtools.vagrant

### ISSUE THREAD

**Issue by zot24** [wunki/django-salted#12]
When I try to run this commando `fab vagrant collectstatic` I get the following error

```
vagrant@vagrant:/vagrant$ fab vagrant collectstatic -f fabfile.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/fabric/main.py", line 594, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/usr/lib/python2.7/dist-packages/fabric/main.py", line 156, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/vagrant/fabfile.py", line 3, in <module>
    from fabtools.vagrant import vagrant
```

Should be fabtools installed after run the command vagrant up?

**Comment by avelis** [comment]
@zot24 Just so others can know, was this issue resolved? Was it user error?

**Comment by zot24** [comment]
Is the same problem than in this Issue https://github.com/wunki/django-salted/issues/11
